[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "exqudens-example"
version = "1.0.0"
description = "Exqudens Example"
requires-python = ">=3"
dependencies = [
    "xmltodict==1.0.2"
]

[project.optional-dependencies]
test = []

[tool.pdm.build]
includes = ["src/main/py"]
package-dir = "src/main/py"
